services:
  server:
    image: lphub:latest
    build:
      context: .
      target: lphub
    container_name: lphub-server
    restart: unless-stopped
    links:
     - database:lphub.database
    volumes:
     - ./backend:/app
  database:
    image: postgres:15.4
    container_name: lphub-db
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: "${DB_NAME}"
    volumes:
      - ./docker/volumes/initdb:/docker-entrypoint-initdb.d
      - ./docker/volumes/postgresql-data:/var/lib/postgresql/data
  proxy:
    image: nginx:stable-alpine3.20
    container_name: lphub-proxy
    links:
      - server:lphub.server
    ports:
      - 80:80
      - 443:443
    environment:
    - NGINX_HOST=lp.hub.local
    - NGINX_PORT=443
    volumes:
    - ./docker/volumes/ssl:/ssl:r
    - ./docker/volumes/nginx:/etc/nginx/templates
    - ./docker/volumes/logs/nginx:/var/log/nginx:rw
    - ./frontend/build:/app:r
    - ./backend/docs/swagger.json:/app/swagger.json:r
